# 머신러닝 기반 텍스트 분류 
1. 데이터 준비 : 로딩, 입력데이터, 출력데이터, 학습/테스트 데이터 분리, 특징 추출
2. 학습-평가 : 
3. 배포 준비

In [67]:
import pandas as pd
datafile = './data/Korean_movie_reviews_2016.csv'
data_df = pd.read_csv(datafile, encoding='utf-8')
data_df.head()

                                              review  label
0                                  부산 행 때문 너무 기대하고 봤      0
1                           한국 좀비 영화 어색하지 않게 만들어졌 놀랍      1
2                        조금 전 보고 왔 지루하다 언제 끝나 이 생각 드      0
3  평 밥 끼 먹자 돈 니 내고 미친 놈 정신사 좀 알 싶어 그래 밥 먹다 먹던 숟가락...      1
4  점수 대가 과 이 엑소 팬 어중간 점수 줄리 없겠 클레멘타인 이후 최고 평점 조작 ...      0

In [68]:
data_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 165384 entries, 0 to 165383
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   review  165384 non-null  str
 1   label   165384 non-null  int64
dtypes: int64(1), str(1)
memory usage: 15.0 MB

In [69]:
# 입력 데이터, 정답 데이터 추출
review_list = list(data_df.review) # 입력 데이터
label_list = list(data_df.label) # 출력 데이터
len(review_list), len(label_list)

(165384, 165384)

In [70]:
# 학습 데이터, 테스트 데이터 분리
from sklearn.model_selection import train_test_split

train_X, test_X, train_Y, test_Y = train_test_split(review_list, label_list, test_size=0.1) 
len(train_X), len(test_X), len(train_Y), len(test_Y)

(148845, 16539, 148845, 16539)

In [71]:
# 한국어 토크나이저 정리 
from konlpy.tag import Okt
def korean_tokenizer(text):
    my_tags = ['Noun', 'Verb', 'Adjective'] # 명사, 동사, 형용사만 추출
    my_stopwords = [] # 불용어 제거
    tokenizer = Okt().pos
    return [word for word, tag in tokenizer(text) if tag in my_tags and word not in my_stopwords] # 길이가 1보다 큰 단어만 반환

In [72]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=1000) # 최대 1000개의 단어만 사용
vectorizer.fit(train_X)

TfidfVectorizer(max_features=1000)

In [73]:
len(vectorizer.get_feature_names_out()), vectorizer.get_feature_names_out()[:10]

(1000,
 array(['가고', '가는', '가면', '가볍', '가서', '가슴', '가장', '가족', '가지', '가치'],
       dtype=object))

In [74]:
# 입력 데이터, 정답 데이터 추출
review_list = list(data_df.review) # 입력 데이터
label_list = list(data_df.label) # 출력 데이터
len(review_list), len(label_list)

(165384, 165384)

In [75]:
# 학습 데이터 특징 추출
from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(review_list, label_list, test_size=0.1)
len(train_X), len(test_X), len(train_y), len(test_y)

(148845, 16539, 148845, 16539)

In [76]:
# 한국어 토크나이저 정의
from konlpy.tag import Okt
def korean_tokenizer(text):
    my_tags = ['Noun', 'Verb', 'Adjective'] # 명사, 동사, 형용사만 추출
    my_stopwords = [] # 불용어 제거
    tokenizer = Okt().pos
    return [word for word, tag in tokenizer(text) if tag in my_tags and word not in my_stopwords] # 길이가 1보다 큰 단어만 반환

In [77]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(tokenizer=korean_tokenizer, max_features=1000) # 최대 1000개의 단어만 사용
vectorizer.fit(train_X)

c:\Users\user\anaconda3\envs\textmine26\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

TfidfVectorizer(max_features=1000,
                tokenizer=<function korean_tokenizer at 0x000001DD12E6EB90>)

In [78]:
len(vectorizer.get_feature_names_out()), vectorizer.get_feature_names_out()[:10]

(1000,
 array(['가', '가고', '가는', '가볍', '가서', '가슴', '가장', '가족', '가지', '각본'],
       dtype=object))

In [79]:
# 학습 데이터 특징 추출
train_X_fv = vectorizer.transform(train_X)

In [80]:
# 텍스트 데이터 특징 추출
test_X_fv = vectorizer.transform(test_X)

In [81]:
#train_x_fv.toarray()[:1]
print(train_X_fv)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1102996 stored elements and shape (148845, 1000)>
  Coords	Values
  (0, 625)	0.36647795442847314
  (0, 630)	0.562512380331912
  (0, 736)	0.5067736360489379
  (0, 769)	0.5407903592862828
  (1, 281)	0.6668422386066187
  (1, 437)	0.44048443711799873
  (1, 625)	0.2237289162276557
  (1, 932)	0.5578891121993258
  (2, 135)	0.33845301553771806
  (2, 254)	0.2596101495039294
  (2, 379)	0.27767562227612025
  (2, 381)	0.24781447985993094
  (2, 382)	0.26148448193316526
  (2, 404)	0.2570382861861282
  (2, 500)	0.36235488503945884
  (2, 585)	0.3257809106891419
  (2, 859)	0.27265707287055013
  (2, 861)	0.17688641729089816
  (2, 875)	0.23687349201130378
  (2, 948)	0.3275311321066504
  (2, 974)	0.1965779790553627
  (3, 83)	0.34737243967645404
  (3, 97)	0.31993497504465324
  (3, 278)	0.2901987760919607
  (3, 349)	0.3365974770434063
  :	:
  (148843, 819)	0.16024731659789165
  (148843, 821)	0.23136962450754703
  (148843, 831)	0.19701799327015643
  (148843, 890)	0.22770215154721107
  (148843, 992)	0.24716978906543577
  (148844, 34)	0.21424334874360637
  (148844, 105)	0.1889473804136666
  (148844, 191)	0.29821265522613566
  (148844, 205)	0.17366307092536604
  (148844, 238)	0.20507517622658777
  (148844, 310)	0.27783464264039287
  (148844, 368)	0.23125884215037246
  (148844, 371)	0.2724142105139124
  (148844, 379)	0.22362216136587687
  (148844, 396)	0.17435043253704194
  (148844, 398)	0.2726434831370574
  (148844, 472)	0.2857491602476963
  (148844, 615)	0.15525417404625547
  (148844, 626)	0.2293539233213725
  (148844, 767)	0.25956859092163775
  (148844, 795)	0.15201681017898364
  (148844, 821)	0.13998396915656586
  (148844, 957)	0.2140570153958449
  (148844, 974)	0.15831131372988633
  (148844, 990)	0.24147158062341972

In [82]:
# 정답 데이터를 ndarray로 변환 np.array(sequence)
import numpy as np
train_y = np.array(train_y)
test_y = np.array(test_y)
print(train_y[:10])

[0 1 1 1 0 0 1 1 1 0]

# 2. 머신러닝 - 모델 학습
1. 의사결정트리, Decision Tree (DT)
2. 랜덤포레스트, RandomForest (RF)

In [83]:
# 모델 별 정확도를 data frame으로 저장하여 비교
import pandas as pd
score_df = pd.DataFrame(columns=['train', 'test'])
score_df

Empty DataFrame
Columns: [train, test]
Index: []

In [84]:
def get_scores(model, train_x, train_y, test_x, test_y):
    train_score = model.score(train_x, train_y) * 100
    test_score = model.score(test_x, test_y) * 100
    return train_score, test_score

### 1. Decision Tree

In [85]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(train_X_fv, train_y)

DecisionTreeClassifier()

In [86]:
train_score, test_score = get_scores(dtc, train_X_fv, train_y, test_X_fv, test_y)
print(train_score, test_score)

98.12422318519265 79.70252131325957

In [87]:
score_df.loc['DecisionTree'] = [train_score, test_score]
score_df

                  train       test
DecisionTree  98.124223  79.702521

### 2. Random Forest

In [88]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1)
rf.fit(train_X_fv, train_y)

RandomForestClassifier(n_jobs=-1)

In [89]:
train_score, test_score = get_scores(rf, train_X_fv, train_y, test_X_fv, test_y)
print(train_score, test_score)
score_df.loc['RandomForest'] = [train_score, test_score]
score_df

98.1222076656925 84.83584255396336

                  train       test
DecisionTree  98.124223  79.702521
RandomForest  98.122208  84.835843

# 3. 나이브 베이즈 분류

In [90]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()
mnb.fit(train_X_fv, train_y)

MultinomialNB()

In [91]:
train_score, test_score = get_scores(mnb, train_X_fv, train_y, test_X_fv, test_y)
print(train_score, test_score)
score_df.loc['NaiveBayes'] = [train_score, test_score]
score_df

85.29409788706373 84.97490779369974

                  train       test
DecisionTree  98.124223  79.702521
RandomForest  98.122208  84.835843
NaiveBayes    85.294098  84.974908

### 4. 로지스틱 회귀 분석, Logistic regression

In [92]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver='liblinear')
lr.fit(train_X_fv, train_y)

LogisticRegression(solver='liblinear')

In [93]:
train_score, test_score = get_scores(lr, train_X_fv, train_y, test_X_fv, test_y)
print(train_score, test_score)
score_df.loc['LogisticRegression'] = [train_score, test_score]
score_df

86.22258053680002 85.7548823991777

                        train       test
DecisionTree        98.124223  79.702521
RandomForest        98.122208  84.835843
NaiveBayes          85.294098  84.974908
LogisticRegression  86.222581  85.754882

### 5. 서포트 벡터 머신, SVM

In [94]:
from sklearn.svm import LinearSVC
svm = LinearSVC()
svm.fit(train_X_fv, train_y)

LinearSVC()

In [95]:
train_score, test_score = get_scores(svm, train_X_fv, train_y, test_X_fv, test_y)
print(train_score, test_score)
score_df.loc['SVM'] = [train_score, test_score]
score_df

86.1453189559609 85.73069714009311

                        train       test
DecisionTree        98.124223  79.702521
RandomForest        98.122208  84.835843
NaiveBayes          85.294098  84.974908
LogisticRegression  86.222581  85.754882
SVM                 86.145319  85.730697

In [96]:
score_df.sort_values(by='test', ascending=False)

                        train       test
LogisticRegression  86.222581  85.754882
SVM                 86.145319  85.730697
NaiveBayes          85.294098  84.974908
RandomForest        98.122208  84.835843
DecisionTree        98.124223  79.702521

### 6. 배포 준비

    기능 구현
    모델 저장

In [97]:
review = '영화가 너무 재미있다'

# 전처리 및 특징 벡터 추출
review_fv = vectorizer.transform([review])
#print(review_fv)
#review_fv.toarray()

def analyze_sentiment(review):
    
    
    review_fv = vectorizer.transform([review])
    result = rf.predict(review_fv)
    #print(result)   

    show = '긍정' if result[0] >= 0.5 else '부정'
    #print(show)
    return show

show = analyze_sentiment(review)
print(f'{review} => {show}')

영화가 너무 재미있다 => 긍정

In [98]:
reviews = {'영화가 너무 재미있다',
    '영화가 너무 지루하다',
    '개꿀잼',
    '핵노잼'
}

for review in reviews:
    print(f'{review} => {analyze_sentiment(review)}')

영화가 너무 지루하다 => 부정
개꿀잼 => 긍정
영화가 너무 재미있다 => 긍정
핵노잼 => 부정

In [99]:
import joblib

vectorizer_file = './model/sa_movie_vectorizer.pkl'
joblib.dump(vectorizer, vectorizer_file)

model_file = './model/sa_movie_model.pkl'
joblib.dump(rf, model_file)

['./model/sa_movie_model.pkl']